export const FETCH_INTERVIEWID_SUCCESS = "FETCH_INTERVIEWID_SUCCESS";
export const FETCH_INTERVIEWID_FAILURE = "FETCH_INTERVIEWID_FAILURE";
export const FETCH_INTERVIEWID_REQEUST = "FETCH_INTERVIEWID_REQEUST";