export const FETCH_NAVER_INTERVIEWTAGS_SUCCESS = "FETCH_NAVER_INTERVIEWTAGS_SUCCESS";
export const FETCH_NAVER_INTERVIEWTAGS_FAILURE = "FETCH_NAVER_INTERVIEWTAGS_FAILURE";
export const FETCH_NAVER_INTERVIEWTAGS_REQUEST = "FETCH_NAVER_INTERVIEWTAGS_REQUEST";