export const FETCH_INTERVIEWTAGS_SUCCESS = "FETCH_INTERVIEWTAGS_SUCCESS";
export const FETCH_INTERVIEWTAGS_FAILURE = "FETCH_INTERVIEWTAGS_FAILURE";
export const FETCH_INTERVIEWTAGS_REQUEST = "FETCH_INTERVIEWTAGS_REQUEST";